---
id: Share
name: Share
full: Resource sharing library
description: A library to access all shared resources a user owns or has access to.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Share
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Db: ^2
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Group: ^2
      pear.horde.org/Horde_Perms: ^2.1
      pear.horde.org/Horde_Support: ^2
      pear.horde.org/Horde_Translation: ^2.2
      pear.horde.org/Horde_Url: ^2
      pear.horde.org/Horde_Util: ^2
  optional:
    pear:
      pear.horde.org/Horde_Kolab_Storage: ^2
      pear.horde.org/Horde_Test: ^2.1
